### ISSUE TITLE
V0.3 Release Plan

### ISSUE THREAD

**Issue by cp5555** [Azure/MS-AMP#92]
# Release Manager
@cp5555 

# Endgame
- [x] Code freeze: Oct. 20th, 2023
- [x] Bug Bash date: Oct. 23rd, 2023
- [x] Release date: Nov. 3rd, 2023 

# Main Features
## MS-AMP Performance Improvement
- [x] 1. Integrate latest TE with MS-AMP (#98)
- [x] 2. Support latest Megatron-LM (#95 and #100)

## MS-AMP O3 Optimization
- [x] 1. Support DistributedDataParallel with FP8-support (#93)
- [x] 2. Integrate with MSCCL (#90)

## MS-AMP Improvement
- [x] 1. Refactor code in dist_op module (#94)
- [x] 2. Support UT for distributed testing

## MS-AMP Demo & Documentation
- [x] 1. Setup MS-AMP Website (Related to #29)

# Backlog

## MS-AMP O3 Optimization
1. Support auto scaling factor tuning (ASFT) for FP8 collective communication (Related to #41)

## MS-AMP Improvement
1. Move extension installation from post install to setup.py (Related to #43)
